class Patient_Report:
    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.email = kwargs.get("email")
        self.role = kwargs.get("role")

        self.patient_id = kwargs.get("patient_id")
        self.age_group = kwargs.get("age_group")
        self.sex = kwargs.get("sex")
        self.smoking_history = kwargs.get("smoking_history")
        self.first_name = kwargs.get("first_name")
        self.last_name = kwargs.get("last_name")

        self.highest_systolic_bp = kwargs.get("highest_reading_systolic_bp")
        self.highest_hba1c = kwargs.get("highest_reading_hba1c")
        self.highest_reading_timestamp = kwargs.get("highest_reading_timestamp")
        self.highest_reading_left_sensory_score = kwargs.get("highest_reading_left_sensory_score")
        self.highest_reading_right_sensory_score = kwargs.get("highest_reading_right_sensory_score")
        self.highest_reading_asymmetry_difference = kwargs.get("highest_reading_asymmetry_difference")
        self.highest_reading_average_asymmetry = kwargs.get("highest_reading_average_asymmetry")
        self.highest_reading_asymmetry_index = kwargs.get("highest_reading_asymmetry_index")
        self.highest_reading_risk_label = kwargs.get("highest_reading_risk_label")

        self.avg_systolic_bp  = kwargs.get("avg_systolic_bp")
        self.avg_hba1c = kwargs.get("avg_hba1c")
        self.avg_left_sensory_score = kwargs.get("avg_left_sensory_score")
        self.avg_right_sensory_score = kwargs.get("avg_right_sensory_score")
        self.avg_asymmetry_difference = kwargs.get("avg_asymmetry_difference")
        self.avg_average_asymmetry = kwargs.get("avg_average_asymmetry")
        self.avg_asymmetry_index = kwargs.get("avg_asymmetry_index")
        self.avg_risk_label = kwargs.get("avg_risk_label")

        self.latest_reading_systolic_bp  = kwargs.get("latest_reading_systolic_bp")
        self.latest_reading_hba1c = kwargs.get("latest_reading_hba1c")
        self.latest_reading_timestamp = kwargs.get("latest_reading_timestamp")
        self.latest_reading_left_sensory_score = kwargs.get("latest_reading_left_sensory_score")
        self.latest_reading_right_sensory_score = kwargs.get("latest_reading_right_sensory_score")
        self.latest_reading_asymmetry_difference = kwargs.get("latest_reading_asymmetry_difference")
        self.latest_reading_average_asymmetry = kwargs.get("latest_reading_average_asymmetry")
        self.latest_reading_asymmetry_index = kwargs.get("latest_reading_asymmetry_index")
        self.latest_reading_risk_label = kwargs.get("latest_reading_risk_label")

        self.doctor_id = kwargs.get("doctor_id")
        self.doctor_first_name = kwargs.get("doctor_first_name")
        self.doctor_last_name = kwargs.get("doctor_last_name")
        self.doctor_title = kwargs.get("doctor_title")
        self.doctor_qualification = kwargs.get("doctor_qualification")
        self.doctor_profession = kwargs.get("doctor_profession")
        self.notes = kwargs.get("notes")
